<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.2.0.0" ProductVersion="3.1.4023.21">
  <POU Name="MAIN" Id="{2a06b1b8-2774-4e8b-aade-9ff87f2c5952}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	ii, jj, kk, ww : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>